version: -"2.3.3"

services:
  postgres:
    image:
      - postgres:latest
    restart:
      - always
    environment:
      - POSTGRES_PASSWORD=dolcevita
      - POSTGRES_DB=todos
    ports:
      - '5432:5432'
    networks:
      - shared-network
    volumes:
      - ./postgres-bd:/var/lib/postegresql/data

  api:
    container_name: todo_api
    restart: unless-stopped
    image: todo-api-prod:1.0.0
    build:
      - context:server
      - target:production
      - dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - shared-network
    depends_on:
      - postgres

  client:
    container_name: todo_client
    restart: unless-stopped
    image: todo-client-prod:1.0.0
    build:
      - context:client
      - target:production
      - dockerfile: Dockerfile
    ports:
      - '5173:5173'
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
