version: '3.8'

services:
  frontend:
    build: ./client/todos
    ports:
      - '5173:5173'

  backend:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - postgres # Backend depends on PostgreSQL being up

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: dolcevita
      POSTGRES_USER: postgres
      POSTGRES_DB: todos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
